# Generated by Django 2.2.5 on 2019-10-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
